version: '3.8'

services:
  # Service 1: Backend Golang
  app:
    container_name: homecare-backend
    build: .
    ports:
      - "8085:8080" # Port VPS : Port Container
    depends_on:
      - db
    restart: always
    env_file:
      - .env

  # Service 2: Database MySQL
  db:
    image: mysql:8.0
    container_name: homecare-db
    cap_add:
      - SYS_NICE  # Fix untuk warning MySQL di beberapa Docker
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql # Agar data tidak hilang saat container restart
    restart: always

volumes:
  db_data: